### ISSUE TITLE
i need a full port, the instructions are still a bit confusing 

### ISSUE THREAD

**Issue by hoaanhmine** [raonygamer/Saturn-Engine#2]

**Comment by raonygamer** [comment]
sorry, I posted the guide by accident, it's not ready yet

**Comment by raonygamer** [comment]
if u want u can call me in raonyreis13#9931

**Comment by raonygamer** [comment]
I'm available in a few hours, sorry, I'm still at work

**Comment by hoaanhmine** [comment]
i was in your discord group, when you are free give me some mods
